require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
